import os
import time
import pygame
pygame.mixer.init()
pygame.mixer.music.load("piel.mp3")
def clear():
    os.system("cls" if os.name == "nt" else "clear")
clear()
pygame.mixer.music.play()
time.sleep(3)
print("beibi")
time.sleep(1.5)
clear()
print("que lo que puedo hacer")
time.sleep(1.75)
print("que lo que puedo hacer")
time.sleep(1.25)
clear()
print("te quiero volver a ver")
time.sleep(1.75)
clear()
print("re")
time.sleep(0.35)
print("cor")
time.sleep(0.5)
print("dan")
time.sleep(0.30)
print("do")
time.sleep(0.5)
print("piel en las fotos")
time.sleep(1.25)
clear()
print("re")
time.sleep(0.35)
print("cor")
time.sleep(0.5)
print("dan")
time.sleep(0.30)
print("do")
time.sleep(0.5)
print("piel en las fotos")
time.sleep(1.25)
clear()
time.sleep(0.65)
print("en mi cama y de copiloto")
time.sleep(3.15)
print("con tu camara de rollo")
time.sleep(2)
print("y estas")
time.sleep(1.15)
clear()
print("en")
time.sleep(0.35)
print("se")
time.sleep(0.5)
print("ñan")
time.sleep(0.30)
print("do")
time.sleep(0.5)
print("piel en las fotos")
time.sleep(1.25)
clear()
print("e-en")
time.sleep(0.35)
print("se")
time.sleep(0.5)
print("ñan")
time.sleep(0.30)
print("do")
time.sleep(0.5)
print("piel en las fotos")
time.sleep(1.25)
clear()
print("ig: lc.xander")
time.sleep(20)
